### ISSUE TITLE
preview images are not showing

### ISSUE THREAD

**Issue by 123khaled123** [RafaelDeJongh/MyAnimeList#1]
Hello, Thank you for sharing this awesome CSS but for somehow preview images are not showing for me. Any idea why?

**Comment by RafaelDeJongh** [comment]
This could be cause by not correctly entering your username where the "ENTERMALUSERNAME" in the url is stated.

For example if I'd use my own username it I'd require to change it to:

@import url("//mal-image.appspot.com/anime/rafaeldejongh/?code=%23more%5BID%5D%7Bbackground-image%3aurl(%5BURL%5D)%7D");

Feel free to let me know if it works!

**Comment by 123khaled123** [comment]
Yep! it actually worked. I totally forgot that part I was too excited to finish it. Thank you for your reply and good stuff you got there <3
