### ISSUE TITLE
I write my name where you said and it does not show up the images, is that cause alot of MAL is down still?

### ISSUE THREAD

**Issue by StaffiiVR** [RafaelDeJongh/MyAnimeList#3]
Title says all.

**Comment by StaffiiVR** [comment]
/*Designed by Rafael De Jongh*/
@import url("//malcat-gen.appspot.com/series?preset=more&user=StaffTroll&list=anime");
@import url("//rafaeldejongh.github.io/MyAnimeList-Classic-RDJ-Theme/styleMAL.css");
License{/*Profile Liststyle created for MyAnimeList.com by Rafael De Jongh - https://github.com/RafaelDeJongh/MyAnimeList*/}
what i wrote for context

**Comment by RafaelDeJongh** [comment]
> is that cause a lot of MAL is down still

Yes the API is down as you might know, so no cover generation is possible.
