### ISSUE TITLE
MAL-Sync

### ISSUE THREAD

**Issue by beastyrabbit** [RafaelDeJongh/MyAnimeList#4]
Hey, I just updated to [MAL-Sync](https://greasyfork.org/de/scripts/372847-mal-sync). 
MAL-Sync => Old Name => KissAnimeList
Now the Layout is messed up. 
https://i.imgur.com/2NsAEOV.jpg

Thank you for your Design and I hope you can fix it. 

Update: I think MAL-Sync replaced the Pictures with High-Res and the Scale is not correct on every Picture.

**Comment by RafaelDeJongh** [comment]
Hey there @Whitedoteu I think you're on in the wrong github repo as to the looks of your screenshot that is the new modern theme which can be found here: https://github.com/RafaelDeJongh/MyAnimeList-Modern-RDJ-Theme

With on top of that, that it looks quite outdated version of it, make sure to grab the latest version and follow the updated installation instructions of that theme. Perhaps that will fix it!
